### PR TITLE
Update cloc to version 1.72

### PR DESCRIPTION
**Pull request by rtfpessoa**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Could you also update the help in the README? Or just remove it?

**Comment by rtfpessoa** [comment]
@kentcdodds just updated.

**Comment by kentcdodds** [comment]
Thanks! I set up automatic releases, so this should be released automatically soon.

**Comment by rtfpessoa** [comment]
@kentcdodds what is the best way for me to know when it is released?

**Comment by kentcdodds** [comment]
It's released already :) https://github.com/kentcdodds/cloc/releases

Thanks!

**Comment by rtfpessoa** [comment]
Nice. Thanks!

**Pull request merged**
