### PR TITLE
feat: auto bump version

### LINKED ISSUE #26: How about using a cron job to bump cloc version automatically?
e.g. use Github Actions to run the update script every week.

I can send a PR for this later!

### PR DESCRIPTION
**Pull request by so1ve**
resolves #26

### CODE REVIEW

**Comment by so1ve** [comment]
@kentcdodds Shall we stop using semantic-version on this repo? I think we'd better follow cloc's version.

**Comment by kentcdodds** [comment]
Unfortunately that would require changing the package name because we're already past the cloc version and we can't publish on top of a previous released version.

**Comment by so1ve** [comment]
> Unfortunately that would require changing the package name because we're already past the cloc version and we can't publish on top of a previous released version.

OK, I understand. So I just need to update the source code and push it to this repo right?

**Comment by kentcdodds** [comment]
What if we do get rid of semantic-release and just multiply the major version by 10?

**Comment by so1ve** [comment]
> What if we do get rid of semantic-release and just multiply the major version by 10?

Seemed to be a nice option!

**Comment by so1ve** [comment]
How about x.x.x-cloc?

**Comment by kentcdodds** [comment]
> How about x.x.x-cloc?

Sounds fine to me. We'll just want to make sure to set the latest tag on npm and I think we can remove the cloc file from git. Also, we'd remove the existing release workflow file.

**Comment by so1ve** [comment]
~~Great - However, it seemed that the files in .gitignore will not be published to npm. Any thoughts?~~
Ah I can add it to "files" (

**Review by kentcdodds — CHANGES_REQUESTED** [review]
Thanks so much for working on this. Could you commit to keeping an eye on this and fixing issues that come up? If so, I'm happy to merge!

**Review by kentcdodds — APPROVED** [review]
Sorry, I meant to mark this as "approved"

**Comment by so1ve** [comment]
> Thanks so much for working on this. Could you commit to keeping an eye on this and fixing issues that come up? If so, I'm happy to merge!

Yes, I would be happy to working on this!

**Comment by so1ve** [comment]
Ah. The workflow is tested without publishing to npm, I'm not sure whether it works or not in your repo :( WDYT?

**Comment by kentcdodds** [comment]
Let's just try it out :)

**Comment by so1ve** [comment]
> Let's just try it out :)

Thanks!
NOTE: To starting publish the package, please change the version in package.json to any value and run the workflow manually in the actions tab.

**Comment by so1ve** [comment]
@kentcdodds Ping :)

**Comment by kentcdodds** [comment]
Looks like it worked!

I've also updated the cron to run every day instead of once a week. It's pretty fast so I don't think that'll be an issue.

Also, it may be useful to add a note to the README explaining the unique characteristics of the version number.

**Comment by so1ve** [comment]
> Looks like it worked!
> 
> I've also updated the cron to run every day instead of once a week. It's pretty fast so I don't think that'll be an issue.
> 
> Also, it may be useful to add a note to the README explaining the unique characteristics of the version number.

Makes sense :)

**Comment by kentcdodds** [comment]
The last run failed because there was no new version. Could you update the script to not fail in that case? It should just log and exit 0

**Comment by so1ve** [comment]
> The last run failed because there was no new version. Could you update the script to not fail in that case? It should just log and exit 0

I need to find a way to let github actions exit without marking the run as "failure"...

**Pull request merged**
