### PR TITLE
fix: discard rest steps when the version does not need to be updated and ignore errors

### PR DESCRIPTION
**Pull request by so1ve**
https://github.com/kentcdodds/cloc/pull/27#issuecomment-1498382935

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
How about instead we just remove the `process.exit(1)`

**Comment by so1ve** [comment]
> How about instead we just remove the `process.exit(1)`

If we remove this line only, the rest steps will still be taken. The `git commit` command will report "working tree clean" and exit with code 1

**Comment by kentcdodds** [comment]
You could replace it with a `return`.

**Comment by so1ve** [comment]
> You could replace it with a `return`.

yeah I have tested it, but it means the process is exited without failure, and the rest steps are still being executed.

**Comment by kentcdodds** [comment]
Ah, I see what you mean. You're talking about the rest of the GitHub action steps. That makes sense. Thanks!

**Pull request merged**
